name: JDK compatibility tests (Runtime)

on:
  push:

jobs:
  test:
    name: "Build ${{ matrix.platform }}: ${{ matrix.build-image }}/${{ matrix.runtime-image }}"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build-image:
          - 11
        runtime-image:
          - 11
          - 11-jre
          - 17
          - 17-jre
          - 18
          - 18-jre
        platform:
          - linux/amd64
          - linux/arm64/v8
          - linux/arm/v7
      fail-fast: false
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: "Build the Docker Image"
        run: |
          docker build \
            --build-arg BUILD_IMAGE=eclipse-temurin:${{ matrix.build-image }} \
            --build-arg RUNTIME_IMAGE=eclipse-temurin:${{ matrix.runtime-image }} \
            --platform ${{ matrix.platform }} \
            --tag test:latest \
            --load \
            .

      - name: "Execute the Docker Image"
        run: |
          docker run \
          --platform ${{ matrix.platform }} \
          test:latest
